### ISSUE TITLE
v2.0.11 won't run on Windows

### ISSUE THREAD

**Issue by faudi** [0xbitcoin/0xbitcoin-gpuminer#2]
Here's what I get trying to execute the newly released executable for Windows. Previously released build (1.5.23) works flawlessly.

`pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module './build/Release/hybridminer'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\0xbitcoin-gpuminer\0xbitcoinminer-accel.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)`

**Comment by 0xbitcoin** [comment]
Thanks for the feedback ! Yes it needs a hybridminer.node built file that has been built in windows using the command


Npm run build

**Comment by faudi** [comment]
Guess it can't be built under linux, that's why it hasn't been uploaded to the repository.

Kk, thanks.

**Comment by faudi** [comment]
I tried building the available pull request, but the resulting hybridminer.node crashes the nvidia driver (390.77) on my Win10 + GTX 960 4GB
Sigh! :)
